version: 2.1
setup: trye
orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  generate-circleci-config:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/purge.yml
          mapping: |
            purge/files.txt purge-cdn-cache-workflow true
