version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2

executors:
  php8:
    docker:
      - image: islamicnetwork/php:8.0-cli
    working_directory: ~/repo
jobs:
  purge-cache:
    executor: php8
    steps:
      - run: echo "test"
  
workflows:
  cdn-purge:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/config.yml
          mapping: |
            purge/files.txt purge-cache true
