version: 2.1

executors:
  php8:
    docker:
      - image: islamicnetwork/php:8.0-cli
    working_directory: ~/repo
jobs:
  purge-cache:
    executor: php8
    steps:
      - run: echo "test"
  
workflows:
  cdn-purge:
    jobs:
      - purge-cache:
          filters:
            branches:
              only: master
          mapping: |
            purge/files.txt purge-cache true
