version: 2.1

parameters:
  purge-cdn-cache-workflow:
    type: boolean
    default: false

executors:
  php8:
    docker:
      - image: islamicnetwork/php:8.0-cli
    working_directory: ~/repo

jobs:
  purge-cache-au:
    executor: php8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:99:a0:64:57:b5:4a:c8:6b:5f:e4:1f:01:7a:69:a3"
      - run:
          command: |
            echo "VerifyHostKeyDNS yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config 
            ssh circleci@au.cdn.islamic.network -p 17700 "git clone git@github.com:islamic-network/cdn.git && cd cdn/purge && ./purge.sh && cd ../../ && rm -rf cdn"
  purge-cache-in:
    executor: php8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:99:a0:64:57:b5:4a:c8:6b:5f:e4:1f:01:7a:69:a3"
      - run:
          command: |
            echo "VerifyHostKeyDNS yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config 
            ssh circleci@in.cdn.islamic.network -p 17700 "git clone git@github.com:islamic-network/cdn.git && cd cdn/purge && ./purge.sh && cd ../../ && rm -rf cdn"
  purge-cache-sg:
    executor: php8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:99:a0:64:57:b5:4a:c8:6b:5f:e4:1f:01:7a:69:a3"
      - run:
          command: |
            echo "VerifyHostKeyDNS yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config 
            ssh circleci@sg.cdn.islamic.network -p 17700 "git clone git@github.com:islamic-network/cdn.git && cd cdn/purge && ./purge.sh && cd ../../ && rm -rf cdn"
  purge-cache-de:
    executor: php8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:99:a0:64:57:b5:4a:c8:6b:5f:e4:1f:01:7a:69:a3"
      - run:
          command: |
            echo "VerifyHostKeyDNS yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config 
            ssh circleci@de.cdn.islamic.network -p 17700 "git clone git@github.com:islamic-network/cdn.git && cd cdn/purge && ./purge.sh && cd ../../ && rm -rf cdn"
  purge-cache-uk:
    executor: php8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:99:a0:64:57:b5:4a:c8:6b:5f:e4:1f:01:7a:69:a3"
      - run:
          command: |
            echo "VerifyHostKeyDNS yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config 
            ssh circleci@uk.cdn.islamic.network -p 17700 "git clone git@github.com:islamic-network/cdn.git && cd cdn/purge && ./purge.sh && cd ../../ && rm -rf cdn"
  purge-cache-us:
    executor: php8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:99:a0:64:57:b5:4a:c8:6b:5f:e4:1f:01:7a:69:a3"
      - run:
          command: |
            echo "VerifyHostKeyDNS yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config 
            ssh circleci@us.cdn.islamic.network -p 17700 "git clone git@github.com:islamic-network/cdn.git && cd cdn/purge && ./purge.sh && cd ../../ && rm -rf cdn"
  purge-cache-ca:
    executor: php8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:99:a0:64:57:b5:4a:c8:6b:5f:e4:1f:01:7a:69:a3"
      - run:
          command: |
            echo "VerifyHostKeyDNS yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config 
            ssh circleci@ca.cdn.islamic.network -p 17700 "git clone git@github.com:islamic-network/cdn.git && cd cdn/purge && ./purge.sh && cd ../../ && rm -rf cdn"
  
workflows:
  purge-cdn-cache-workflow:
    when: << pipeline.parameters.purge-cdn-cache-workflow >>
    jobs:
      - purge-cache-au:
          filters:
            branches:
              only: master
      - purge-cache-in:
          filters:
            branches:
              only: master
      - purge-cache-sg:
          filters:
            branches:
              only: master
      - purge-cache-de:
          filters:
            branches:
              only: master
      - purge-cache-uk:
          filters:
            branches:
              only: master
      - purge-cache-us:
          filters:
            branches:
              only: master
      - purge-cache-ca:
          filters:
            branches:
              only: master
