version: 2.1

parameters:
  purge-cdn-cache-workflow:
    type: boolean
    default: false

executors:
  php8:
    docker:
      - image: islamicnetwork/php:8.0-cli
    working_directory: ~/repo

jobs:
  purge-cache-br:
    executor: php8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:99:a0:64:57:b5:4a:c8:6b:5f:e4:1f:01:7a:69:a3"
      - run:
          command: |
            cat VerifyHostKeyDNS yes >> ~/.ssh/config
            cat StrictHostKeyChecking no >> ~/.ssh/config 
            ssh circleci@br.cdn.islamic.network -p 17700
            echo "We got here" >> /home/circleci/build.txt
  
workflows:
  purge-cdn-cache-workflow:
    when: << pipeline.parameters.purge-cdn-cache-workflow >>
    jobs:
      - purge-cache-br:
          filters:
            branches:
              only: master
