version: 2.1

parameters:
  purge-cdn-cache-workflow:
    type: boolean
    default: false

executors:
  php8:
    docker:
      - image: islamicnetwork/php:8.0-cli
    working_directory: ~/repo
jobs:
  purge-cache:
    executor: php8
    steps:
      - run: echo "test"
  
workflows:
  purge-cdn-cache-workflow:
    when: << pipeline.parameters.purge-cdn-cache-workflow >>
    jobs:
      - purge-cache:
          filters:
            branches:
              only: master
