version: '3.9'
services:
  #######################################
  # NGINX Docker container
  #######################################
  nginx:
    image: ghcr.io/islamic-network/cdn:dubai-26

#      context: .
#      dockerfile: Dockerfile
    environment:
      #ISLAMIC_NETWORK_CDN_ORIGIN: "cdn.islamic.network.eu-central-1.linodeobjects.com"
      ISLAMIC_NETWORK_CDN_ORIGIN: "cdn.islamic.network.ap-south-1.linodeobjects.com"
      ALADHAN_CDN_ORIGIN: "cdn.aladhan.com.ap-south-1.linodeobjects.com"
      LOCAL_CDN_HOSTNAME: "cdn.karachi.islamic.network"
      POP: "Karachi"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cdn:/var/cache/cdn
      - certs:/etc/certs
    privileged: true
    container_name: islamic-network-cdn
    deploy:
      update_config:
        order: start-first
    logging:
      driver: "gelf"
      options:
        gelf-address: "tcp://gl.mamluk.net:12201"
        tag: "cdn-karachi"

volumes:
  cdn:
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/.acme.sh/cdn.islamic.network
