name: Deploy to Dubai PoP
on:
  workflow_dispatch: 
  push:
    branches:
      - master
    paths:
      - "deploy/docker-compose-dubai.yml"
jobs:
  Update-Dubai-PoP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: cdn.dubai.islamic.network
          username: ubuntu
          key:  ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            sudo -S sh -c 'cd /home/ubuntu/cdn && git pull origin master --rebase && cd /home/ubuntu/cdn/deploy && docker compose -f docker-compose-dubai.yml up -d'