name: Deploy to Newark PoP
on:
  workflow_dispatch: 
  push:
    paths:
      - "deploy/docker-compose-newark.yml"
jobs:
  Update-Newark-PoP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: cdn.newark.islamic.network
          username: ${{ secrets.SSH_USER }}
          key:  ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo -S sh -c 'cd /root/cdn && git pull origin master --rebase && cd /root/cdn/deploy && docker compose -f docker-compose-newark.yml up -d'