name: Deploy to Karachi PoP
on:
  workflow_dispatch: 
  push:
    branches:
      - master
    paths:
      - "deploy/docker-compose-karachi.yml"
jobs:
  Update-Dubai-PoP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: cdn.karachi.islamic.network
          username: ${{ secrets.SSH_USER }}
          key:  ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            sudo -S sh -c 'cd /root/cdn && git pull origin master --rebase && cd /root/cdn/deploy && docker compose -f docker-compose-karachi.yml up -d'